export const AUTH_TYPES = {
    AUTH_USER: "AUTH_USER",
    UNAUTH_USER: "UNAUTH_USER",
    AUTH_ERROR: "AUTH_ERROR"
};

export const POKEMON_TYPES = {
    FETCH_POKEMONS: "FETCH_POKEMONS",
    FETCH_FAVORITES: "FETCH_FAVORITES",
    SET_FILTER: "SET_FILTER",
    SET_TYPES: "SET_TYPES",
    CHANGE_PAGE: "CHANGE_PAGE",
    START_FETCHING: "START_FETCHING",
    END_FETCHING: "END_FETCHING",
    ADD_FAVORITE: "ADD_FAVORITE",
    CLEAR_FAVORITES: "CLEAR_FAVORITES",
    REMOVE_FAVORITE: "REMOVE_FAVORITE"
};
