export const AUTH_TYPES = {
    AUTH_USER: "AUTH_USER",
    UNAUTH_USER: "UNAUTH_USER",
    AUTH_ERROR: "AUTH_ERROR"
};

export const POKEMON_TYPES = {
    FETCH_POKEMONS: "FETCH_POKEMONS",
    FILTER_POKEMONS: "FILTER_POKEMONS",
    CHANGE_PAGE: "CHANGE_PAGE",
    START_FETCHING: "START_FETCHING",
    END_FETCHING: "END_FETCHING"
};
